#!/usr/bin/env python
# -*- coding:utf-8 -*-
import argparse

from new_markdown import Markdown

if __name__ == '__main__':
    md = Markdown()

    parser = argparse.ArgumentParser('Parse markdown to html.')
    parser.add_argument('--input', '-i', help='input markdown file')
    parser.add_argument('--output', '-o', help="output html file")

    args = parser.parse_args()
    with open(args.input, 'r') as fin:
        output = md.convert(fin.read())
        with open(args.output, 'w') as fout:
            fout.write(output)
